"""user table

Revision ID: a46825d6fe96
Revises: cbb24e293eec
Create Date: 2023-02-23 13:19:43.203645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46825d6fe96'
down_revision = 'cbb24e293eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_user_password')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_password', ['password'], unique=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
